// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20211204_V1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20211204_V1));
        
        string IMigrationMetadata.Id
        {
            get { return "202112050242313_20211204_V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
